services:
  reverse-proxy:
    container_name: where-name-proxy
    build:
      context: ./apps/reverse-proxy
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "8080:8080"
    volumes:
      - ./apps/reverse-proxy/Caddyfile:/etc/caddy/Caddyfile
      - ./apps/reverse-proxy/caddy_data:/data
      - ./apps/reverse-proxy/caddy_config:/config
    environment:
      - PORT=8080
      - FRONTEND_ENDPOINT=http://frontend:3000
      - BACKEND_ENDPOINT=http://backend:4000

  frontend:
    container_name: where-name-frontend
    build:
      context: ./apps/frontend-js
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_POSTHOG_KEY: ${POSTHOG_API_KEY}
        NEXT_PUBLIC_POSTHOG_ENABLED: ${POSTHOG_ENABLED}
        NEXT_PUBLIC_APP_ENV: ${APP_ENV}
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: where-name-backend
    build:
      context: ./apps/backend-go
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://where_name_user:where_name_password@postgres:5432/where_name_db?sslmode=disable
      - ALLOWED_ORIGINS=http://localhost:3000,http://localhost
      - COOKIE_SECURE=false
      - POSTHOG_API_KEY=${POSTHOG_API_KEY}
      - POSTHOG_HOST=${POSTHOG_HOST}
      - POSTHOG_ENABLED=${POSTHOG_ENABLED}
      - APP_ENV=${APP_ENV}
    ports:
      - '4000:4000'
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: where-name-postgres
    environment:
      POSTGRES_USER: where_name_user
      POSTGRES_PASSWORD: where_name_password
      POSTGRES_DB: where_name_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
